#!/bin/bash

_bb_completion() {
	local current_word subcommands
	COMPREPLY=()
	current_word="${COMP_WORDS[COMP_CWORD]}"

	bashbox_home=$(bb home_dir)

	# Dynamically get a list of subcommands from functions in the "commands" directory
	# TODO - cant hard-code this
	subcommands=$(for file in "${bashbox_home}"/commands/*.bash; do
		grep -E '^[a-zA-Z_][a-zA-Z0-9\._]*[[:space:]]*\(\)' "$file" |   # find the function lines
			sed -E 's/^([a-zA-Z_][a-zA-Z0-9\._]*)[[:space:]]*\(\).*/\1/' | # grab name and remove "() {"
			grep -vE '^_' |                                                # remove internal functions
			sed -e "s/^bb\.//"                                             # remove bb. prefix

	done | tr '\n' ' ')

	if [ $COMP_CWORD -eq 1 ]; then
		# Autocomplete subcommands
		COMPREPLY=($(compgen -W "$subcommands" -- "$current_word"))
	fi
}

complete -F _bb_completion bb
